### ISSUE TITLE
module script types do not need to listen to DOMContentLoaded

### ISSUE THREAD

**Issue by akii0008** [JackDotJS/node-studio#13]
https://github.com/JackDotJS/node-studio/blob/87b787004cb477b7e25a2d92d38c9fb30158bdb0/assets/scripts/core.mjs#L3

this is unnecessary here.

![image](https://user-images.githubusercontent.com/26691026/178556360-4d56a4b0-5fb2-445f-9713-20f6d4a69866.png)

**Comment by JackDotJS** [comment]
holy god damn fuck how long has this been a thing

**Comment by JackDotJS** [comment]
done in 1e47b9e
