### ISSUE TITLE
convert to typescript

### ISSUE THREAD

**Issue by JackDotJS** [JackDotJS/node-studio#22]
this is one of my last remaining projects that uses plain JS/Node.JS, and I think this one in particular would absolutely benefit from the things TS has to offer.

the only thing im worried about is this: how this will work with the whole browser context stuff? will modules still work as intended? how can we set it up so the browser scripts get compiled to mjs, while all the node scripts get compiled to regular js?

or do we even need to worry about that at all?? idk

@akii0008 i would especially like your feedback on this

**Comment by akii0008** [comment]
> the only thing im worried about is this: how this will work with the whole browser context stuff? 

this is not difficult. typescript had dom types built in, you just have to enable it.

> will modules still work as intended? 

yes they will

> how can we set it up so the browser scripts get compiled to mjs, while all the node scripts get compiled to regular js?

typescript uses modules by default, that's not something we need to worry about.

**Comment by akii0008** [comment]
all you'll need to do is make electron point to the build folder instead of the src folder. when i get off work today i'll open a PR with the necessary changes

**Comment by JackDotJS** [comment]
yes pls and ty 🧡
